name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Babel Building
      - run: npm run build
      - name: Jest Tests
      - run: npm test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build files
          path: build/*.js
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage/clover.xml
          directory: ./coverage/lcov-report/
          name: codecov-umbrella
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true